name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install Packages
      - name: Install Dependencies
        run: npm install

      # Step 4: Build Project
      - name: Build App
        run: npm run build

      # Step 5: Upload Build (Preview)
      - name: Upload Build Files
        uses: actions/upload-artifact@v4
        with:
          name: build-preview
          path: dist/
